networks:
    app-network:

volumes:
    app-data:

services:
    nginx:
        image: nginx:1.27-alpine
        ports:
            - '8350:80'
        volumes:
            - ./:/var/www
            - .docker/settings/nginx:/etc/nginx/conf.d
            - .docker/logs/nginx:/var/log/nginx
        networks:
            app-network:
        # restart: always
    workspace:
        build:
            context: .docker
            dockerfile: Dockerfile_83
        image: workspace_laravel_php_8315_core
        volumes:
            - ./:/var/www
            - .docker/settings/php/php-custom.ini:/usr/local/etc/php/conf.d/local.ini
            - .docker/logs/php:/var/log/php
        networks:
            app-network:
        # restart: always
