<?php

/**
 * constants-upload.php
 */
defined('DS') or define('DS', DIRECTORY_SEPARATOR);

// DIR, File
define('PERMISSION_DIR', 0775);
define('PERMISSION_FILE', 0775);

define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml', 'image/bmp', 'image/x-icon']);
// dont resize
define('NON_RESIZABLE_TYPES', ['svg', 'gif']);

// upload size limit
define('MIN_FILE_UPLOAD_SIZE', '10KB');
define('MAX_FILE_UPLOAD_SIZE', '5MB');
define('MIN_IMAGE_UPLOAD_SIZE', '10KB');
define('MAX_IMAGE_UPLOAD_SIZE', '5MB');

// backend default image size
define('DEFAULT_PROFILE_IMAGE', 'img/icons/user-bg.png');
define('DEFAULT_IMAGE_SIZE_600', 'img/no-image/600x400.png');

// Image/File Uploads
define('STORAGE_DIR_NAME', 'storage');
define('APP_STORAGE_PATH', 'app' . DS . 'public' . DS);

// Basic Image Size - Width
defined('IMAGE_WIDTH_30') or define('IMAGE_WIDTH_30', 30);
define('IMAGE_WIDTH_50', 50);
define('IMAGE_WIDTH_90', 90);
define('IMAGE_WIDTH_100', 100);
define('IMAGE_WIDTH_130', 130);
define('IMAGE_WIDTH_190', 190);
define('IMAGE_WIDTH_200', 200);
define('IMAGE_WIDTH_250', 250);
define('IMAGE_WIDTH_360', 360);
define('IMAGE_WIDTH_400', 400);
define('IMAGE_WIDTH_470', 470);
defined('IMAGE_WIDTH_500') or define('IMAGE_WIDTH_500', 500);
define('IMAGE_WIDTH_550', 550);
define('IMAGE_WIDTH_575', 575);
define('IMAGE_WIDTH_600', 600);
define('IMAGE_WIDTH_630', 630);
define('IMAGE_WIDTH_700', 700);
define('IMAGE_WIDTH_780', 780);
define('IMAGE_WIDTH_800', 800);
defined('IMAGE_WIDTH_1200') or define('IMAGE_WIDTH_1200', 1200);
define('IMAGE_WIDTH_1355', 1355);
define('IMAGE_WIDTH_1920', 1920);

// Default values
define('UPLOAD_FILE_DIR_NAME_TMP', 'tmp');
define('UPLOAD_FILE_DIR_NAME', 'uploads');
define('UPLOAD_FILE_PATH', APP_STORAGE_PATH . UPLOAD_FILE_DIR_NAME);
define('UPLOAD_FILE_MAX_SIZE', 2000);
define('UPLOAD_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));

// Album Module
define('ALBUM_FILE_DIR_NAME', 'album');
define('ALBUM_FILE_PATH', APP_STORAGE_PATH . ALBUM_FILE_DIR_NAME);
define('ALBUM_FILE_MAX_SIZE', 2000);
define('ALBUM_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_360, IMAGE_WIDTH_500, IMAGE_WIDTH_600, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));

// Blog Category Module
define('BLOG_CATEGORY_FILE_DIR_NAME', 'blogcategory');
define('BLOG_CATEGORY_FILE_PATH', APP_STORAGE_PATH . BLOG_CATEGORY_FILE_DIR_NAME);
define('BLOG_CATEGORY_FILE_MAX_SIZE', 2000);
define('BLOG_CATEGORY_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800]));

// Blog Module
define('BLOG_FILE_DIR_NAME', 'blog');
define('BLOG_FILE_PATH', APP_STORAGE_PATH . BLOG_FILE_DIR_NAME);
define('BLOG_FILE_MAX_SIZE', 2000);
define('BLOG_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_360, IMAGE_WIDTH_400, IMAGE_WIDTH_600, IMAGE_WIDTH_800, IMAGE_WIDTH_1200, IMAGE_WIDTH_1355]));

// BANNER Module
define('BANNER_FILE_DIR_NAME', 'banner');
define('BANNER_FILE_PATH', APP_STORAGE_PATH . BANNER_FILE_DIR_NAME);
define('BANNER_FILE_MAX_SIZE', 2000);
define('BANNER_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1920, IMAGE_WIDTH_630]));

// Page Module
define('PAGE_FILE_DIR_NAME', 'page');
define('PAGE_FILE_PATH', APP_STORAGE_PATH . PAGE_FILE_DIR_NAME);
define('PAGE_FILE_MAX_SIZE', 2000);
define('PAGE_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));

// News Module
define('NEWS_FILE_DIR_NAME', 'news');
define('NEWS_FILE_PATH', APP_STORAGE_PATH . NEWS_FILE_DIR_NAME);
define('NEWS_FILE_MAX_SIZE', 2000);
define('NEWS_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_360, IMAGE_WIDTH_400, IMAGE_WIDTH_780, IMAGE_WIDTH_800, IMAGE_WIDTH_1200, IMAGE_WIDTH_1355]));

// Post Module
define('POST_FILE_DIR_NAME', 'post');
define('POST_FILE_PATH', APP_STORAGE_PATH . POST_FILE_DIR_NAME);
define('POST_FILE_MAX_SIZE', 2000);
define('POST_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_190, IMAGE_WIDTH_360, IMAGE_WIDTH_400, IMAGE_WIDTH_800, IMAGE_WIDTH_1200, IMAGE_WIDTH_1355]));

// Post Category Module
define('POST_CATEGORY_FILE_DIR_NAME', 'postCategory');
define('POST_CATEGORY_FILE_PATH', APP_STORAGE_PATH . POST_CATEGORY_FILE_DIR_NAME);
define('POST_CATEGORY_FILE_MAX_SIZE', 2000);
define('POST_CATEGORY_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));

// FAQ Category Module
define('FAQ_CATEGORY_FILE_DIR_NAME', 'faqCategory');
define('FAQ_CATEGORY_FILE_PATH', APP_STORAGE_PATH . FAQ_CATEGORY_FILE_DIR_NAME);
define('FAQ_CATEGORY_FILE_MAX_SIZE', 2000);
define('FAQ_CATEGORY_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));

// Testimonial Module
define('TESTIMONIAL_FILE_DIR_NAME', 'testimonial');
define('TESTIMONIAL_FILE_PATH', APP_STORAGE_PATH . TESTIMONIAL_FILE_DIR_NAME);
define('TESTIMONIAL_FILE_MAX_SIZE', 2000);
define('TESTIMONIAL_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));
// RESOURCES Module
define('RESOURCE_FILE_DIR_NAME', 'resource');
define('RESOURCE_FILE_PATH', APP_STORAGE_PATH . RESOURCE_FILE_DIR_NAME);
define('RESOURCE_FILE_MAX_SIZE', 2000);
define('RESOURCE_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));
define('RESOURCE_FILE_ALLOWED_TYPES', ['pdf', 'doc', 'docx']);

// Site Setting Module
define('SITE_SETTING_FILE_DIR_NAME', 'siteSetting');
define('SITE_SETTING_FILE_PATH', APP_STORAGE_PATH . SITE_SETTING_FILE_DIR_NAME);
define('SITE_SETTING_FILE_MAX_SIZE', 2000);
define('SITE_SETTING_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));

// User Module
define('USER_FILE_DIR_NAME', 'user');
define('USER_FILE_PATH', APP_STORAGE_PATH . USER_FILE_DIR_NAME);
define('USER_FILE_MAX_SIZE', 2000);
define('USER_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_90, IMAGE_WIDTH_200]));
// Video Module
define('VIDEO_ALBUM_FILE_DIR_NAME', 'videoAlbum');
define('VIDEO_ALBUM_FILE_PATH', APP_STORAGE_PATH . VIDEO_ALBUM_FILE_DIR_NAME);
define('VIDEO_ALBUM_FILE_MAX_SIZE', 2000);
define('VIDEO_ALBUM_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_200, IMAGE_WIDTH_800, IMAGE_WIDTH_1200]));

// Site Sns Module
define('SNS_FILE_DIR_NAME', 'sns');
define('SNS_FILE_PATH', APP_STORAGE_PATH . SNS_FILE_DIR_NAME);
define('SNS_FILE_MAX_SIZE', 2000);
define('SNS_FILE_DIMENSIONS', json_encode([IMAGE_WIDTH_100, IMAGE_WIDTH_30, IMAGE_WIDTH_200]));
